### ISSUE TITLE
Install dds_lab

### ISSUE THREAD

**Issue by gngdb** [edinburghlivinglab/livinglab-hubserver#3]

**Comment by ewan-klein** [comment]
@gngdb Any chance you could get this fixed today?

**Comment by franciscovargas** [comment]
We will both be in the forum working tonight. I think Gavin is not free till 8pm.

**Comment by gngdb** [comment]
To properly close this I have to rebuild the base image (and the server), which will take more time. I'm just going to patch the running container right now, and set that running.

**Comment by franciscovargas** [comment]
There is a particular module in dds_lab which generates a geo_json that has
a voronoi tess based on certain constraints. This module is not dynamically
used by any of the notebooks only the geo_jsons are used. I am bringing
this up here because for the voronoi tessalations to be mapped in to a
geojson I used shapely which has quite a lot of heavy installation problems
and is currently in the requirements. I can take it out of the requirements
since this module is really a script that only needs to be ran once or
twice to generate the geojsons for the map data notebooks. Should I remove
shapely from the requirement list ?

**Comment by gngdb** [comment]
Don't worry about that. I have more problems with the igraph requirement at the moment. I'll get them both installed in the end; at the moment I strip them out at build time.

**Comment by gngdb** [comment]
OK, running server now patched.
